apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stag

resources:
  - ../../../base-migrations

patches:
  - path: runtime-config.yaml

labels:
  - pairs:
      app.kubernetes.io/name: workshop-app
      app.kubernetes.io/part-of: workshop

images:
  - name: workshop-app
    newName: workshop-app
    newTag: latest
