apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: workshop-app
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: workshop-app
        app.kubernetes.io/component: api
      annotations:
        ad.datadoghq.com/api.logs: '[{"source":"nodejs","service":"workshop-app"}]'
    spec:
      containers:
        - name: api
          image: workshop-app
          imagePullPolicy: IfNotPresent
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://$(DD_AGENT_HOST):4317"
          envFrom:
            - configMapRef:
                name: workshop-app-config
            - secretRef:
                name: workshop-app-secret
          ports:
            - containerPort: 3000
              name: http
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
