apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - hpa.yaml
  - ingress.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: workshop-app
      app.kubernetes.io/part-of: workshop
    includeSelectors: true

images:
  - name: workshop-app
    newName: workshop-app
    newTag: latest
